version: 2

models:
  - name: stg_customers
    description: "Cleaned customer dimension from the raw olist customer table"

    columns:

      - name: customer_id
        description: "Primary key for each customer."
        tests:
          - unique
          - not_null 

      - name: customer_unique_id
        description: "Identifier representing the same customer across multiple orders."

      - name: zip_code_prefix
        description: "Customer ZIP code prefix."

      - name: city
        description: "Customer city."

      - name: state
        description: "Customer state."
      
  - name: stg_orders
    description: "Cleaned orders table from the raw olist dataset."

    columns:

      - name: order_id
        description: "Unique Identifier for each order."
        tests:
          - unique 
          - not_null 
      
      - name: customer_id
        description: "Customer associated with the order."
        tests:
          - not_null 
      
      - name: order_status
        description: "Current status of the order."

      - name: order_purchase_timestamp
        description: "Timestamp when the order was placed."
      
      - name: order_approved_at
        description: "Timestamp when payment was approved."

      - name: order_delivered_carrier_date
        description: "Timestamp when the carrier received the order."

      - name: order_delivered_customer_date
        description: "Timestamp when the cusotmer received the order."
      
      - name: order_estimated_delivery_date
        description: "Estimated delivery date."